FILTER_RANGE = [20, 40]
HIGHPASS_FREQ = 0.3
BASE_SAMPLE_RATE = 250
IDUN_SAMPLE_RATE = 250

FIRST_LAG_EPOCH_SIZE = BASE_SAMPLE_RATE * 60
SECOND_LAG_EPOCH_SIZE = BASE_SAMPLE_RATE * 30  # 30 works best
TOTAL_LINEAR_SEGMENTS = 1000

# Prodigy configuration
CHANNEL_1 = "LEFT_EYE"
CHANNEL_2 = "RIGHT_EYE"
PRODIGY_SAMPLE_RATE = 120
